"""empty message

Revision ID: 2ea156aa993a
Revises: 
Create Date: 2018-11-04 15:09:55.923331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea156aa993a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=100), nullable=False),
    sa.Column('author_name', sa.String(length=30), nullable=False),
    sa.Column('book_dept', sa.String(length=20), nullable=False),
    sa.Column('book_cost', sa.String(length=20), nullable=False),
    sa.Column('book_des', sa.String(length=10000), nullable=False),
    sa.Column('year_published', sa.String(length=20), nullable=False),
    sa.Column('book_pub', sa.String(length=50), nullable=False),
    sa.Column('isbn_number', sa.String(length=20), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('no_of_pages', sa.Integer(), nullable=False),
    sa.Column('no_of_copies', sa.Integer(), nullable=False),
    sa.Column('no_ofCopies', sa.Integer(), nullable=False),
    sa.Column('floor_no', sa.Integer(), nullable=False),
    sa.Column('rack_no', sa.Integer(), nullable=False),
    sa.Column('shelf_no', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn_number')
    )
    op.create_table('borrow_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('book_name', sa.String(length=100), nullable=False),
    sa.Column('author_name', sa.String(length=20), nullable=False),
    sa.Column('book_dept', sa.String(length=20), nullable=False),
    sa.Column('isbn_number', sa.String(length=20), nullable=False),
    sa.Column('borrow_time', sa.DateTime(), nullable=False),
    sa.Column('renew_time', sa.DateTime(), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('fine', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn_number')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=100), nullable=False),
    sa.Column('author_name', sa.String(length=20), nullable=False),
    sa.Column('book_dept', sa.String(length=20), nullable=False),
    sa.Column('isbn_number', sa.String(length=20), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('typeofmembership', sa.String(length=20), nullable=False),
    sa.Column('no_of_copies', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_name'),
    sa.UniqueConstraint('isbn_number')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alpha_2', sa.String(length=5), nullable=False),
    sa.Column('alpha_3', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('numeric', sa.String(length=10), nullable=False),
    sa.Column('official_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('book_name', sa.String(length=20), nullable=False),
    sa.Column('author_name', sa.String(length=20), nullable=False),
    sa.Column('book_dept', sa.String(length=20), nullable=False),
    sa.Column('book_implementation', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('door_no', sa.String(length=3), nullable=False),
    sa.Column('street_name', sa.String(length=70), nullable=False),
    sa.Column('area_name', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('postal_code', sa.String(length=7), nullable=False),
    sa.Column('mobile_number', sa.String(length=14), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('typeofmembership', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('security', sa.String(length=20), nullable=False),
    sa.Column('Account_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('requestion')
    op.drop_table('country')
    op.drop_table('cart')
    op.drop_table('borrow_book')
    op.drop_table('books')
    # ### end Alembic commands ###
